# Generated by Django 4.0.1 on 2023-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('selected_batch', models.CharField(max_length=10)),
                ('payment_details', models.CharField(max_length=255)),
                ('enrollment_date', models.DateField()),
                ('enrolled_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
